### ISSUE TITLE
Add in README documentation about editing the root prompt

### ISSUE THREAD

**Issue by msilini-lvmh** [rbourgeat/ImpAI#1]
By having the ability to edit the root prompt more easily we could slave-trade adventurers for potions with more ease
![image](https://github.com/rbourgeat/ImpAI/assets/133097129/e1d1aa2d-9b8e-41ef-8fe5-3e22fb2234f0)

**Comment by rbourgeat** [comment]
Done ! ([here](https://github.com/rbourgeat/ImpAI#%EF%B8%8F-config))
