### ISSUE TITLE
Virtual environment

### ISSUE THREAD

**Issue by Hukasx0** [rbourgeat/ImpAI#4]
I recommend considering running the software in a virtual environment like anaconda (miniconda) to avoid problems with python versions as well as libraries for python.
https://docs.conda.io/projects/miniconda/en/latest/
https://conda.io/projects/conda/en/latest/user-guide/getting-started.html

**Comment by rbourgeat** [comment]
Thank you for this issue (and for the MR) !

Yes I forgot to add miniconda because i use it by default 😅

I add this soon 👌🏻

**Comment by rbourgeat** [comment]
@Hukasx0 done here https://github.com/rbourgeat/ImpAI/pull/6 !
