### ISSUE TITLE
Can gguf run on GPU? 

### ISSUE THREAD

**Issue by atljoseph** [rbourgeat/ImpAI#8]
Got the make completed with llama cuda 1, but not running on gpu. Also set cuda visible devices.

**Comment by rbourgeat** [comment]
ImpAI work with CUDA but if you use the dockerized version, it run on CPU.
Can you provide me the logs if you have any? 

Thanks

**Comment by atljoseph** [comment]
Am running the source directly from a script based on start.sh. Run logs
for llama.cpp? Or build logs? Thanks

**Comment by rbourgeat** [comment]
Oh mb, you edit the start.sh with `make LLAMA_CUDA=1` and that not work ?

**Comment by atljoseph** [comment]
In Ubuntu. It installed just fine. But I saw no such env variable in the
source I ran. I added it eventually. But after research. Made no
difference.

Do you want build logs for cpp server or run logs??

**Comment by rbourgeat** [comment]
llama cpp server logs please :)

**Comment by atljoseph** [comment]
Thank you. I did read the front end code just now. Yeah looks like a single
url and json schema tweak could work wonderfully for the text ui. Still
wanna make sure I understand the llama cpp server, since I think I had the
same problem elsewhere. It’s a good tool to have tamed. Will get those logs
to you today or tonight.

**Comment by atljoseph** [comment]
Does this impart enough info? Ollama, stable diffusion and xorg currently utilize the GPU just fine. Although I’m a bit confused between seeing references to 8.6, 11.5, 12.2, and 12.4 in the various outputs here. 

![IMG_1776](https://github.com/rbourgeat/ImpAI/assets/25017621/550282c9-3f3a-4bfd-9424-8f4e78dd508e)
![IMG_1775](https://github.com/rbourgeat/ImpAI/assets/25017621/d14c3440-4403-4a31-bcd3-3041948b450f)
![IMG_1774](https://github.com/rbourgeat/ImpAI/assets/25017621/ca417a37-5849-4a21-8a6b-c0b52045cf77)
![IMG_1773](https://github.com/rbourgeat/ImpAI/assets/25017621/4f855f9e-3491-4780-baf7-ee550bb46869)
![IMG_1777](https://github.com/rbourgeat/ImpAI/assets/25017621/7e43df7a-2e20-4f8e-a147-a23fab9b3110)

**Comment by rbourgeat** [comment]
8.6, 11.5, 12.2, and 12.4 are the different version of CUDA driver

**Comment by atljoseph** [comment]
I get that. Just not understanding if that is just something that exists or
if it is part of my problem. Gonna just try Ollama tonight. Really wish I
could figure it out haha.

**Comment by atljoseph** [comment]
Ok I found a path issue that was making my cuda toolkit version not in any
way match my cuda drivers. Now the drivers are on 12.4 and toolkit on 12.2,
so really close, with toolkit slightly lower. Still running into the same
issue. Am beginning to think that it just builds fine, but something is
still configured wrong … either on my system or the arguments/env used for
the build are causing unexpected runtime behavior.

**Comment by atljoseph** [comment]
Ok got it up and running on gpu. What was it? Ended up doing make clean and
then make LLAMA_CUDA=1
LLAMA_CUDA_F16=false. After that, everything loaded up just fine. Idk :/
