### ISSUE TITLE
I see the chat model file. But where is the stable diffusion image?

### ISSUE THREAD

**Issue by atljoseph** [rbourgeat/ImpAI#9]
What is this local files only flag? And AutoPipelineForText2Image? It’s like it gets the image from somewhere magically. But hey, it is running. Chat and image.

**Comment by rbourgeat** [comment]
The `local_files_only=True` flag is for don't try to download model if they already downloaded (in the Hugging Face cache) and the `AutoPipelineForText2Image` is for load the Stable Diffusion model into the RAM/VRAM.
